# Generated by Django 5.2 on 2025-04-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_job_title'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Policy Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weekday_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Weekday Rate Multiplier')),
                ('weekend_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Weekend Rate Multiplier')),
                ('holiday_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=4, verbose_name='Holiday Rate Multiplier')),
                ('night_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Night Rate Multiplier')),
                ('night_start_time', models.TimeField(default='22:00:00', verbose_name='Night Time Start')),
                ('night_end_time', models.TimeField(default='06:00:00', verbose_name='Night Time End')),
                ('max_daily_hours', models.PositiveSmallIntegerField(default=12, verbose_name='Maximum Daily Hours')),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=60, verbose_name='Maximum Weekly Hours')),
                ('requires_manager_approval', models.BooleanField(default=True, verbose_name='Requires Manager Approval')),
                ('requires_justification', models.BooleanField(default=True, verbose_name='Requires Justification')),
                ('min_notice_hours', models.PositiveSmallIntegerField(default=24, help_text='Minimum hours of notice required before overtime', verbose_name='Minimum Notice Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Overtime Policy',
                'verbose_name_plural': 'Overtime Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Estimated Hours')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Actual Hours')),
                ('reason', models.TextField(verbose_name='Reason for Overtime')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_requests', to='employees.employee', verbose_name='Approved By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee', verbose_name='Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='projects.project', verbose_name='Project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='projects.task', verbose_name='Task')),
                ('time_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_request', to='projects.timeentry', verbose_name='Related Time Entry')),
            ],
            options={
                'verbose_name': 'Overtime Request',
                'verbose_name_plural': 'Overtime Requests',
                'ordering': ['-date', '-requested_at'],
            },
        ),
    ]
