# Generated by Django 5.2 on 2025-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(upload_to='storage/employee_documents/'),
        ),
    ]
