# Generated by Django 5.2 on 2025-04-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('STAFF_MANAGER', 'Staff Manager'), ('MANAGER', 'Manager')], default='STAFF', max_length=20),
        ),
    ]
