# Generated by Django 5.2 on 2025-04-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeedocument_document_file'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='departments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='employees.employee'),
        ),
    ]
