# Generated by Django 5.2 on 2025-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_employeecontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('PROBATION', 'Probation')], max_length=20),
        ),
    ]
