# Generated by Django 5.2 on 2025-04-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_alter_employee_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại nghỉ phép')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã loại nghỉ phép')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('paid', models.BooleanField(default=True, verbose_name='Được trả lương')),
                ('max_days_per_year', models.PositiveIntegerField(default=12, verbose_name='Số ngày tối đa/năm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('require_approval', models.BooleanField(default=True, verbose_name='Yêu cầu phê duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loại nghỉ phép',
                'verbose_name_plural': 'Loại nghỉ phép',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chế độ')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã chế độ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Số giờ làm việc tiêu chuẩn mỗi ngày', max_digits=4, verbose_name='Số giờ làm việc/ngày')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chế độ làm việc',
                'verbose_name_plural': 'Chế độ làm việc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('half_day', models.BooleanField(default=False, verbose_name='Nghỉ nửa ngày')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối'), ('canceled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktime.leavetype')),
            ],
            options={
                'verbose_name': 'Đơn nghỉ phép',
                'verbose_name_plural': 'Đơn nghỉ phép',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_modes', to='employees.employee')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktime.workmode')),
            ],
            options={
                'verbose_name': 'Chế độ làm việc của nhân viên',
                'verbose_name_plural': 'Chế độ làm việc của nhân viên',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_type', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tổng số ngày')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Số ngày đã dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktime.leavetype')),
            ],
            options={
                'verbose_name': 'Số dư ngày nghỉ',
                'verbose_name_plural': 'Số dư ngày nghỉ',
                'ordering': ['-year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
