# Generated by Django 5.2 on 2025-04-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_alter_employee_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_type', to='employees.employee')),
            ],
        ),
    ]
