# Generated by Django 5.2 on 2025-04-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_job_title'),
        ('worktime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeworkmode',
            options={'ordering': ['-start_date'], 'verbose_name': 'Employee Work Mode', 'verbose_name_plural': 'Employee Work Modes'},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year'], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name'], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AlterModelOptions(
            name='workmode',
            options={'ordering': ['name'], 'verbose_name': 'Work Mode', 'verbose_name_plural': 'Work Modes'},
        ),
        migrations.AddField(
            model_name='workmode',
            name='break_duration_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Break time duration in minutes', verbose_name='Break Duration (min)'),
        ),
        migrations.AddField(
            model_name='workmode',
            name='flexible_hours',
            field=models.BooleanField(default=False, help_text='Allow employees to have flexible working hours', verbose_name='Flexible Hours'),
        ),
        migrations.AddField(
            model_name='workmode',
            name='requires_check_in',
            field=models.BooleanField(default=True, help_text='Require employees to check in', verbose_name='Requires Check-in'),
        ),
        migrations.AddField(
            model_name='workmode',
            name='working_days_per_week',
            field=models.PositiveSmallIntegerField(default=5, help_text='Standard working days per week', verbose_name='Working Days/Week'),
        ),
        migrations.AlterField(
            model_name='employeeworkmode',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='employeeworkmode',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='employeeworkmode',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total Days'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Used Days'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee', verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='half_day',
            field=models.BooleanField(default=False, verbose_name='Half Day'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(default=12, verbose_name='Max Days Per Year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Paid Leave'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='require_approval',
            field=models.BooleanField(default=True, verbose_name='Requires Approval'),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mode Code'),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mode Name'),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='working_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Standard working hours per day', max_digits=4, verbose_name='Working Hours/Day'),
        ),
        migrations.CreateModel(
            name='WorkModeOverrideDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_working_day', models.BooleanField(default=False, help_text="Mark as working day if it's a makeup day, otherwise a holiday", verbose_name='Working Day')),
                ('description', models.CharField(blank=True, help_text='Description of special day (e.g. National Holiday, Makeup day)', max_length=255, null=True, verbose_name='Description')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_dates', to='worktime.workmode', verbose_name='Work Mode')),
            ],
            options={
                'verbose_name': 'Special Date',
                'verbose_name_plural': 'Special Dates',
                'ordering': ['date'],
                'unique_together': {('work_mode', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Day of Week')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Working Day')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='Break Start Time')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='Break End Time')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='worktime.workmode', verbose_name='Work Mode')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['work_mode', 'day_of_week'],
                'unique_together': {('work_mode', 'day_of_week')},
            },
        ),
    ]
