# Generated by Django 5.2 on 2025-04-17 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_job_title'),
        ('worktime', '0002_alter_employeeworkmode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('first_check_in', models.DateTimeField(blank=True, null=True, verbose_name='First Check-in')),
                ('last_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Last Check-out')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('overtime', 'Overtime'), ('half_day', 'Half Day'), ('leave', 'On Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend')], default='absent', max_length=20, verbose_name='Status')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Hours')),
                ('is_complete', models.BooleanField(default=False, help_text='Indicates if both check-in and check-out are recorded', verbose_name='Is Complete')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Daily Attendance Summary',
                'verbose_name_plural': 'Daily Attendance Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now, verbose_name='Record Date')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Record Time')),
                ('record_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End')], max_length=20, verbose_name='Record Type')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('late', 'Late'), ('early', 'Early Leave'), ('overtime', 'Overtime'), ('absent', 'Absent'), ('excused', 'Excused')], default='normal', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Info')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_manual', models.BooleanField(default=False, help_text='Indicates if the record was added manually by admin', verbose_name='Manual Entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_records', to='employees.employee', verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Employee')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='worktime.dailyattendancesummary', verbose_name='Attendance Summary')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-record_date', '-record_time'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['employee', 'date'], name='worktime_da_employe_f361fe_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['date'], name='worktime_da_date_f84ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['status'], name='worktime_da_status_b57351_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancesummary',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'record_date'], name='worktime_at_employe_b24934_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['record_date'], name='worktime_at_record__ab1a39_idx'),
        ),
    ]
